[package]
name = "rireq"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
csv = "1.1.6"
redb = "0.12.0"
serde = { version = "1.0.127", features = ["derive"] }
