name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup macOS
        if: ${{ runner.os == 'macOS' }}
        run: rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
